<a href="https://colab.research.google.com/github/Bougriba/Deeplearning/blob/main/Predict_whether_the_customer_will_stay_or_leave_the_bank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [402]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [403]:
tf.__version__

'2.13.0'

In [404]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [405]:
unique_gender_values = dataset['Gender'].unique()
unique_values

array(['Female', 'Male'], dtype=object)

In [406]:
unique_Geographe_values = dataset['Geography'].unique()
unique_Geographe_values

array(['France', 'Spain', 'Germany'], dtype=object)

In [407]:
dataset.info

<bound method DataFrame.info of       RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfP

In [408]:
X = dataset.iloc[:,3:13].values
y = dataset.iloc[:,-1].values


In [409]:
X[0]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [410]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))



In [411]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,4] = le.fit_transform(X[:,4])

In [412]:
values = []
for i in X[0]:
  values.append(i)
values

[1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88]

In [413]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2, random_state=0)


In [414]:
X_train[0]

array([0.0, 0.0, 1.0, 667, 0, 34, 5, 0.0, 2, 1, 0, 163830.64],
      dtype=object)

In [415]:
print(X_train[:,3:4])

[[667]
 [427]
 [535]
 ...
 [738]
 [590]
 [623]]


In [416]:
X_train[:,3:4].shape

(8000, 1)

In [417]:
reshaped_array=X_train[:,3:4].shape[0]

In [418]:
from sklearn.preprocessing import StandardScaler
sc_CreditScore = StandardScaler()
sc_EstimatedSalary = StandardScaler()
sc_Balance = StandardScaler()
X_train[:,3:4] = sc_CreditScore.fit_transform(X_train[:,3:4])
X_test[:,3:4] = sc_CreditScore.fit_transform(X_test[:,3:4])
X_train[:,11:12] = sc_EstimatedSalary.fit_transform(X_train[:,11:12])
X_test[:,11:12] = sc_EstimatedSalary.fit_transform(X_test[:,11:12])
X_train[:,4:5] = sc_Balance.fit_transform(X_train[:,4:5])
X_test[:,4:5] = sc_Balance.fit_transform(X_test[:,4:5])


In [419]:
X_train[0]

array([0.0, 0.0, 1.0, 0.16958176236487524, -1.0916871447066732, 34, 5,
       0.0, 2, 1, 0, 1.1064316603959772], dtype=object)

In [420]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [421]:
X_train = X_train.astype(np.float32)
y_train = y_train.astype(np.int32)

In [430]:

model = Sequential(
    				[

        				Dense(6, activation='relu', name = 'layer1'),
                Dense(6,activation='relu' , name='layer2'),
        				Dense(1, activation='sigmoid', name = 'layer3')
     				]
			)
model.compile(
    			loss = tf.keras.losses.BinaryCrossentropy(),
   		 	optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
        metrics=['accuracy'],
			)

model.fit(
    		X_train,y_train,
    		epochs=100,
			)


Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 234.3689 - accuracy: 0.7190
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 112.1052 - accuracy: 0.7141
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 63.9528 - accuracy: 0.7181
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 24.0011 - accuracy: 0.7286
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4846 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4825 - accuracy: 0.7960
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4820 - accuracy: 0.7960
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4807 - accuracy: 0.7960
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4798 - 

In [423]:
CreditScore_Array = [[600]]
EstimatedSalary_Array=[[50000]]
Balance_Array=[[1222148]]
CreditScore = sc_CreditScore.transform(CreditScore_Array)
EstimatedSalary = sc_EstimatedSalary.transform(EstimatedSalary_Array)
Balance = sc_Balance.transform(Balance_Array)

In [431]:
print(model.predict([[1,0,0,600,1,40,30,60000,2,1,1,50000]]) > 0.5)

1/1 [==============================] - 0s 125ms/step
[[ True]]


In [432]:
X_test = X_test.astype(np.float32)
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
np.set_printoptions(precision=2)
print(np.concatenate ( ( y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1) ),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [433]:
 from sklearn.metrics import confusion_matrix , accuracy_score

In [434]:
 confusion_matrix(y_test, y_pred)


array([[1576,   19],
       [ 372,   33]])

In [435]:
 accuracy_score(y_test, y_pred)

0.8045